export const authStyles = {
  container: {
    minHeight: '100vh',
    display: 'flex',
    backgroundColor: '#f9fafb',
  },
  leftPanel: {
    flex: 1,
    background: 'linear-gradient(135deg, #8b5cf6 0%, #7c3aed 100%)',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    padding: '4rem',
    color: 'white',
    position: 'relative',
    overflow: 'hidden',
  },
  leftPanelOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    background: 'radial-gradient(circle at top right, rgba(255,255,255,0.1) 0%, transparent 60%)',
    pointerEvents: 'none',
  },
  brandSection: {
    textAlign: 'center',
    zIndex: 1,
    maxWidth: '500px',
  },
  logoIcon: {
    width: '80px',
    height: '80px',
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    borderRadius: '20px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    margin: '0 auto 2rem',
    backdropFilter: 'blur(10px)',
  },
  brandTitle: {
    fontSize: '2.5rem',
    fontWeight: '700',
    marginBottom: '1rem',
    lineHeight: 1.2,
  },
  brandSubtitle: {
    fontSize: '1.125rem',
    opacity: 0.9,
    fontWeight: '400',
    marginBottom: '3rem',
    lineHeight: 1.6,
  },
  featureList: {
    textAlign: 'left',
    display: 'flex',
    flexDirection: 'column',
    gap: '1.5rem',
  },
  featureItem: {
    display: 'flex',
    alignItems: 'flex-start',
    gap: '1rem',
  },
  featureIcon: {
    width: '24px',
    height: '24px',
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    borderRadius: '6px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  featureText: {
    fontSize: '0.9375rem',
    lineHeight: 1.5,
  },
  rightPanel: {
    flex: 1,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '2rem',
  },
  formContainer: {
    width: '100%',
    maxWidth: '480px',
  },
  formHeader: {
    marginBottom: '2.5rem',
  },
  formTitle: {
    fontSize: '2rem',
    fontWeight: '600',
    color: '#111827',
    marginBottom: '0.5rem',
  },
  formSubtitle: {
    fontSize: '0.9375rem',
    color: '#6b7280',
  },
  alert: {
    padding: '1rem',
    borderRadius: '0.5rem',
    marginBottom: '1.5rem',
    fontSize: '0.875rem',
    fontWeight: '500',
    display: 'flex',
    alignItems: 'center',
    gap: '0.75rem',
    backgroundColor: '#fef2f2',
    color: '#991b1b',
    border: '1px solid #fee2e2',
  },
  form: {
    display: 'flex',
    flexDirection: 'column',
    gap: '1.25rem',
  },
  formGroup: {
    display: 'flex',
    flexDirection: 'column',
    gap: '0.5rem',
  },
  label: {
    fontSize: '0.875rem',
    fontWeight: '500',
    color: '#374151',
  },
  inputWrapper: {
    position: 'relative',
  },
  input: {
    width: '100%',
    padding: '0.75rem 1rem',
    paddingLeft: '3rem',
    border: '1px solid #e5e7eb',
    borderRadius: '0.5rem',
    fontSize: '0.9375rem',
    color: '#111827',
    backgroundColor: '#ffffff',
    transition: 'all 0.2s',
    outline: 'none',
  },
  inputIcon: {
    position: 'absolute',
    left: '1rem',
    top: '50%',
    transform: 'translateY(-50%)',
    color: '#9ca3af',
  },
  submitButton: {
    width: '100%',
    padding: '0.875rem',
    backgroundColor: '#8b5cf6',
    color: '#ffffff',
    border: 'none',
    borderRadius: '0.5rem',
    fontSize: '0.9375rem',
    fontWeight: '600',
    cursor: 'pointer',
    transition: 'all 0.2s',
    marginTop: '0.5rem',
  },
  divider: {
    display: 'flex',
    alignItems: 'center',
    gap: '1rem',
    margin: '1.5rem 0',
  },
  dividerLine: {
    flex: 1,
    height: '1px',
    backgroundColor: '#e5e7eb',
  },
  dividerText: {
    fontSize: '0.875rem',
    color: '#6b7280',
  },
  toggleSection: {
    textAlign: 'center',
    marginTop: '1.5rem',
    paddingTop: '1.5rem',
    borderTop: '1px solid #e5e7eb',
  },
  toggleText: {
    fontSize: '0.875rem',
    color: '#6b7280',
  },
  toggleButton: {
    backgroundColor: 'transparent',
    border: 'none',
    color: '#8b5cf6',
    fontWeight: '600',
    fontSize: '0.875rem',
    cursor: 'pointer',
    padding: 0,
    marginLeft: '0.25rem',
  },
  footer: {
    position: 'absolute',
    bottom: '2rem',
    left: '50%',
    transform: 'translateX(-50%)',
    fontSize: '0.875rem',
    color: 'rgba(255, 255, 255, 0.8)',
    textAlign: 'center',
  },

  // Responsive
  '@media (max-width: 768px)': {
    leftPanel: {
      display: 'none',
    },
  },
};