export const dashboardStyles = {
  container: {
    minHeight: '100vh',
    backgroundColor: '#f9fafb',
    paddingTop: '72px', // Height of fixed navbar
  },
  layout: {
    display: 'flex',
    minHeight: 'calc(100vh - 72px)',
  },
  sidebar: {
    width: '240px',
    backgroundColor: '#ffffff',
    borderRight: '1px solid #e5e7eb',
    padding: '1.5rem 0',
    position: 'fixed',
    top: '72px',
    bottom: 0,
    overflowY: 'auto',
  },
  sidebarNav: {
    display: 'flex',
    flexDirection: 'column',
    gap: '0.25rem',
    padding: '0 1rem',
  },
  navItem: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.75rem',
    padding: '0.75rem 1rem',
    backgroundColor: 'transparent',
    border: 'none',
    borderRadius: '0.5rem',
    cursor: 'pointer',
    fontSize: '0.875rem',
    fontWeight: '500',
    color: '#6b7280',
    transition: 'all 0.15s',
    textAlign: 'left',
    position: 'relative',
  },
  navItemActive: {
    backgroundColor: '#f3f4f6',
    color: '#8b5cf6',
  },
  badge: {
    position: 'absolute',
    right: '1rem',
    backgroundColor: '#ef4444',
    color: 'white',
    fontSize: '0.75rem',
    padding: '0.125rem 0.5rem',
    borderRadius: '9999px',
    fontWeight: '600',
  },
  main: {
    flex: 1,
    marginLeft: '240px', // Width of sidebar
    padding: '2rem',
    overflow: 'auto',
  },
  alert: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.75rem',
    padding: '1rem',
    borderRadius: '0.5rem',
    border: '1px solid',
    marginBottom: '1.5rem',
    fontSize: '0.875rem',
    fontWeight: '500',
  },
  alertClose: {
    marginLeft: 'auto',
    background: 'none',
    border: 'none',
    cursor: 'pointer',
    padding: '0.25rem',
    color: 'inherit',
  },
  pageHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: '2rem',
  },
  pageTitle: {
    fontSize: '1.875rem',
    fontWeight: '600',
    color: '#111827',
    margin: '0 0 0.25rem 0',
  },
  pageSubtitle: {
    fontSize: '0.875rem',
    color: '#6b7280',
    margin: 0,
  },
  statsGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))',
    gap: '1.5rem',
    marginBottom: '2rem',
  },
  statCard: {
    backgroundColor: '#ffffff',
    padding: '1.5rem',
    borderRadius: '0.75rem',
    border: '1px solid #e5e7eb',
  },
  statCardHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '1rem',
  },
  statCardTitle: {
    fontSize: '0.875rem',
    fontWeight: '500',
    color: '#6b7280',
  },
  statCardValue: {
    fontSize: '2rem',
    fontWeight: '600',
    color: '#111827',
    marginBottom: '0.5rem',
  },
  statCardFooter: {
    fontSize: '0.75rem',
    fontWeight: '500',
  },
  section: {
    marginTop: '3rem',
  },
  sectionTitle: {
    fontSize: '1.25rem',
    fontWeight: '600',
    color: '#111827',
    marginBottom: '1rem',
  },
  quickActions: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(250px, 1fr))',
    gap: '1.5rem',
  },
  quickActionCard: {
    backgroundColor: '#ffffff',
    padding: '2rem',
    borderRadius: '0.75rem',
    border: '1px solid #e5e7eb',
    cursor: 'pointer',
    textAlign: 'center',
    transition: 'all 0.2s',
  },
  quickActionTitle: {
    fontSize: '1.125rem',
    fontWeight: '600',
    color: '#111827',
    margin: '1rem 0 0.5rem 0',
  },
  quickActionDesc: {
    fontSize: '0.875rem',
    color: '#6b7280',
    margin: 0,
  },
  contentCard: {
    backgroundColor: '#ffffff',
    padding: '2rem',
    borderRadius: '0.75rem',
    border: '1px solid #e5e7eb',
  },
  formGroup: {
    marginBottom: '1.5rem',
  },
  formLabel: {
    display: 'block',
    fontSize: '0.875rem',
    fontWeight: '500',
    color: '#374151',
    marginBottom: '0.5rem',
  },
  uploadZone: {
    border: '2px dashed #d1d5db',
    borderRadius: '0.5rem',
    padding: '3rem 1rem',
    textAlign: 'center',
    backgroundColor: '#fafafa',
    cursor: 'pointer',
    transition: 'all 0.2s',
  },
  uploadZoneLabel: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    cursor: 'pointer',
  },
  uploadZoneText: {
    fontSize: '0.875rem',
    fontWeight: '500',
    color: '#374151',
    margin: '0.75rem 0 0.25rem 0',
  },
  uploadZoneHint: {
    fontSize: '0.75rem',
    color: '#9ca3af',
    margin: 0,
  },
  hiddenInput: {
    display: 'none',
  },
  primaryButton: {
    width: '100%',
    padding: '0.75rem 1.5rem',
    backgroundColor: '#8b5cf6',
    color: '#ffffff',
    border: 'none',
    borderRadius: '0.5rem',
    fontSize: '0.875rem',
    fontWeight: '600',
    cursor: 'pointer',
    transition: 'all 0.2s',
  },
  dangerButton: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.5rem',
    padding: '0.625rem 1rem',
    backgroundColor: '#ef4444',
    color: '#ffffff',
    border: 'none',
    borderRadius: '0.5rem',
    fontSize: '0.875rem',
    fontWeight: '600',
    cursor: 'pointer',
  },
  resultSection: {
    marginTop: '2rem',
    paddingTop: '2rem',
    borderTop: '1px solid #e5e7eb',
  },
  resultHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '1.5rem',
  },
  resultTitle: {
    fontSize: '1.125rem',
    fontWeight: '600',
    color: '#111827',
    margin: 0,
  },
  statusBadge: {
    padding: '0.375rem 0.875rem',
    borderRadius: '0.375rem',
    fontSize: '0.75rem',
    fontWeight: '600',
  },
  resultGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(4, 1fr)',
    gap: '1rem',
    marginBottom: '1.5rem',
  },
  resultMetric: {
    display: 'flex',
    flexDirection: 'column',
    gap: '0.25rem',
  },
  resultMetricLabel: {
    fontSize: '0.75rem',
    color: '#6b7280',
    fontWeight: '500',
  },
  resultMetricValue: {
    fontSize: '1.5rem',
    fontWeight: '600',
    color: '#111827',
  },
  violationsList: {
    marginTop: '1.5rem',
  },
  violationsListTitle: {
    fontSize: '1rem',
    fontWeight: '600',
    color: '#111827',
    marginBottom: '1rem',
  },
  violationItem: {
    padding: '1rem',
    backgroundColor: '#f9fafb',
    borderRadius: '0.5rem',
    marginBottom: '0.75rem',
    border: '1px solid #e5e7eb',
  },
  violationItemHeader: {
    marginBottom: '0.75rem',
  },
  violationBadge: {
    display: 'inline-block',
    padding: '0.25rem 0.625rem',
    borderRadius: '0.25rem',
    fontSize: '0.75rem',
    fontWeight: '600',
  },
  violationText: {
    fontSize: '0.875rem',
    color: '#374151',
    marginBottom: '0.5rem',
    lineHeight: '1.5',
  },
  violationExplanation: {
    fontSize: '0.8125rem',
    color: '#6b7280',
    fontStyle: 'italic',
    margin: 0,
  },
  moreViolations: {
    textAlign: 'center',
    fontSize: '0.875rem',
    color: '#6b7280',
    marginTop: '0.5rem',
  },
  actionSection: {
    marginTop: '1.5rem',
    paddingTop: '1.5rem',
    borderTop: '1px solid #e5e7eb',
  },
  actionSectionTitle: {
    fontSize: '1rem',
    fontWeight: '600',
    color: '#111827',
    marginBottom: '1rem',
  },
  viewFileLink: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '0.5rem',
    padding: '0.625rem 1rem',
    backgroundColor: '#3b82f6',
    color: '#ffffff',
    borderRadius: '0.5rem',
    fontSize: '0.875rem',
    fontWeight: '500',
    textDecoration: 'none',
    marginBottom: '1rem',
  },
  actionButtons: {
    display: 'flex',
    gap: '1rem',
  },
  approveButton: {
    flex: 1,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '0.5rem',
    padding: '0.75rem',
    backgroundColor: '#10b981',
    color: '#ffffff',
    border: 'none',
    borderRadius: '0.5rem',
    fontSize: '0.875rem',
    fontWeight: '600',
    cursor: 'pointer',
  },
  rejectButton: {
    flex: 1,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '0.5rem',
    padding: '0.75rem',
    backgroundColor: '#ef4444',
    color: '#ffffff',
    border: 'none',
    borderRadius: '0.5rem',
    fontSize: '0.875rem',
    fontWeight: '600',
    cursor: 'pointer',
  },
  tableHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '1.5rem',
    gap: '1rem',
  },
  searchBar: {
    flex: 1,
    display: 'flex',
    alignItems: 'center',
    gap: '0.75rem',
    padding: '0.625rem 1rem',
    backgroundColor: '#f9fafb',
    border: '1px solid #e5e7eb',
    borderRadius: '0.5rem',
  },
  searchInput: {
    flex: 1,
    border: 'none',
    backgroundColor: 'transparent',
    fontSize: '0.875rem',
    color: '#111827',
    outline: 'none',
  },
  filterGroup: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.5rem',
  },
  filterSelect: {
    padding: '0.625rem 1rem',
    border: '1px solid #e5e7eb',
    borderRadius: '0.5rem',
    fontSize: '0.875rem',
    color: '#374151',
    backgroundColor: '#ffffff',
    cursor: 'pointer',
  },
  table: {
    width: '100%',
    borderCollapse: 'collapse',
  },
  tableHeaderRow: {
    borderBottom: '1px solid #e5e7eb',
  },
  tableHeaderCell: {
    padding: '0.75rem 1rem',
    textAlign: 'left',
    fontSize: '0.75rem',
    fontWeight: '600',
    color: '#6b7280',
    textTransform: 'uppercase',
    letterSpacing: '0.05em',
  },
  tableRow: {
    borderBottom: '1px solid #f3f4f6',
    transition: 'background-color 0.15s',
  },
  tableCell: {
    padding: '1rem',
    fontSize: '0.875rem',
    color: '#374151',
  },
  fileCell: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.75rem',
  },
  filename: {
    fontWeight: '500',
    color: '#111827',
  },
  tableBadge: {
    display: 'inline-block',
    padding: '0.25rem 0.625rem',
    borderRadius: '0.25rem',
    fontSize: '0.75rem',
    fontWeight: '600',
  },
  chunkMetrics: {
    display: 'flex',
    gap: '0.375rem',
    fontSize: '0.8125rem',
    fontWeight: '500',
  },
  dateText: {
    fontSize: '0.8125rem',
    color: '#6b7280',
  },
  actionButton: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '0.375rem',
    padding: '0.5rem 0.875rem',
    backgroundColor: '#f9fafb',
    border: '1px solid #e5e7eb',
    borderRadius: '0.375rem',
    fontSize: '0.8125rem',
    fontWeight: '500',
    color: '#374151',
    cursor: 'pointer',
  },
  emptyState: {
    textAlign: 'center',
    padding: '4rem 2rem',
  },
  emptyStateText: {
    fontSize: '1.125rem',
    fontWeight: '500',
    color: '#6b7280',
    margin: '1rem 0 0.5rem 0',
  },
  emptyStateHint: {
    fontSize: '0.875rem',
    color: '#9ca3af',
    margin: 0,
  },
  policyList: {
    marginTop: '2rem',
    paddingTop: '2rem',
    borderTop: '1px solid #e5e7eb',
  },
  policyListTitle: {
    fontSize: '1rem',
    fontWeight: '600',
    color: '#111827',
    marginBottom: '1rem',
  },
  policyItem: {
    display: 'flex',
    alignItems: 'center',
    gap: '1rem',
    padding: '1rem',
    backgroundColor: '#f9fafb',
    borderRadius: '0.5rem',
    marginBottom: '0.75rem',
    border: '1px solid #e5e7eb',
  },
  policyDetails: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    gap: '0.25rem',
  },
  policyName: {
    fontSize: '0.875rem',
    fontWeight: '500',
    color: '#111827',
  },
  policyMeta: {
    fontSize: '0.75rem',
    color: '#6b7280',
  },
  modal: {
    position: 'fixed',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 1000,
    padding: '2rem',
  },
  modalContent: {
    backgroundColor: '#ffffff',
    borderRadius: '0.75rem',
    width: '100%',
    maxWidth: '900px',
    maxHeight: '90vh',
    overflow: 'hidden',
    display: 'flex',
    flexDirection: 'column',
    boxShadow: '0 20px 25px -5px rgba(0, 0, 0, 0.1)',
  },
  modalHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    padding: '1.5rem 2rem',
    borderBottom: '1px solid #e5e7eb',
  },
  modalTitle: {
    fontSize: '1.5rem',
    fontWeight: '600',
    color: '#111827',
    margin: '0 0 0.25rem 0',
  },
  modalSubtitle: {
    fontSize: '0.875rem',
    color: '#6b7280',
    margin: 0,
  },
  closeButton: {
    background: 'none',
    border: 'none',
    cursor: 'pointer',
    color: '#6b7280',
    padding: '0.25rem',
  },
  modalBody: {
    padding: '2rem',
    overflow: 'auto',
  },
  modalStats: {
    display: 'grid',
    gridTemplateColumns: 'repeat(5, 1fr)',
    gap: '1rem',
    marginBottom: '2rem',
  },
  modalStatItem: {
    display: 'flex',
    flexDirection: 'column',
    gap: '0.5rem',
  },
  modalStatLabel: {
    fontSize: '0.75rem',
    color: '#6b7280',
    fontWeight: '500',
  },
  modalStatValue: {
    fontSize: '1.5rem',
    fontWeight: '600',
    color: '#111827',
  },
  modalSection: {
    marginTop: '2rem',
  },
  modalSectionTitle: {
    fontSize: '1.125rem',
    fontWeight: '600',
    color: '#111827',
    marginBottom: '1rem',
  },
  modalViolationItem: {
    padding: '1rem',
    backgroundColor: '#f9fafb',
    borderRadius: '0.5rem',
    marginBottom: '0.75rem',
    border: '1px solid #e5e7eb',
  },
  modalViolationHeader: {
    marginBottom: '0.75rem',
  },
  modalViolationText: {
    fontSize: '0.875rem',
    color: '#374151',
    marginBottom: '0.5rem',
    lineHeight: '1.5',
  },
  modalViolationExplanation: {
    fontSize: '0.8125rem',
    color: '#6b7280',
    fontStyle: 'italic',
    margin: 0,
  },
  modalActionSection: {
    marginTop: '2rem',
    paddingTop: '2rem',
    borderTop: '1px solid #e5e7eb',
  },
  modalFinalVerdict: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: '2rem',
    paddingTop: '2rem',
    borderTop: '1px solid #e5e7eb',
  },
};