# Generated by Django 5.2.7 on 2025-10-04 23:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModerationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='moderation_files/')),
                ('filename', models.CharField(max_length=255)),
                ('verdict', models.CharField(choices=[('clean', 'Clean'), ('violation_found', 'Violation Found'), ('error', 'Error')], max_length=20)),
                ('total_chunks', models.IntegerField(default=0)),
                ('allowed_chunks', models.IntegerField(default=0)),
                ('review_chunks', models.IntegerField(default=0)),
                ('violation_chunks', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderation_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Moderation Result',
                'verbose_name_plural': 'Moderation Results',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PolicyDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='policies/')),
                ('filename', models.CharField(max_length=255)),
                ('file_size', models.IntegerField(help_text='File size in bytes')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policy_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Policy Document',
                'verbose_name_plural': 'Policy Documents',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ViolationDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_id', models.CharField(max_length=255)),
                ('chunk_text', models.TextField()),
                ('verdict', models.CharField(choices=[('violation', 'Violation'), ('review', 'Review'), ('unclear', 'Unclear'), ('error', 'Error')], max_length=20)),
                ('explanation', models.TextField()),
                ('sources', models.JSONField(default=list)),
                ('moderation_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violations', to='moderation.moderationresult')),
            ],
            options={
                'verbose_name': 'Violation Detail',
                'verbose_name_plural': 'Violation Details',
                'ordering': ['id'],
            },
        ),
    ]
