# Generated by Django 5.2.7 on 2025-10-05 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moderationresult',
            name='final_verdict',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved - Clean'), ('rejected', 'Rejected - Violation')], default='pending', help_text="User's final decision after review", max_length=20),
        ),
        migrations.AddField(
            model_name='moderationresult',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
