# Generated by Django 5.2.7 on 2025-10-07 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0002_moderationresult_final_verdict_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moderationresult',
            name='verdict',
            field=models.CharField(choices=[('clean', 'Clean'), ('needs_review', 'Needs Review'), ('violation_found', 'Violation Found'), ('error', 'Error')], max_length=20),
        ),
    ]
